// Geo seed data: countries + states
// Format: countries = [ [name, iso2, phone_code, sort_order], ... ]
// Format: states = { 'ISO2': [ [name, code], ... ], ... }

const countries = [
  // Popular / high-traffic countries first (sort_order 1-20)
  ['United States', 'US', '+1', 1],
  ['India', 'IN', '+91', 2],
  ['United Kingdom', 'GB', '+44', 3],
  ['United Arab Emirates', 'AE', '+971', 4],
  ['Saudi Arabia', 'SA', '+966', 5],
  ['Canada', 'CA', '+1', 6],
  ['Australia', 'AU', '+61', 7],
  ['Germany', 'DE', '+49', 8],
  ['Qatar', 'QA', '+974', 9],
  ['Kuwait', 'KW', '+965', 10],
  ['Pakistan', 'PK', '+92', 11],
  ['Bangladesh', 'BD', '+880', 12],
  ['Oman', 'OM', '+968', 13],
  ['Bahrain', 'BH', '+973', 14],
  ['Malaysia', 'MY', '+60', 15],
  ['Philippines', 'PH', '+63', 16],
  ['Nigeria', 'NG', '+234', 17],
  ['Egypt', 'EG', '+20', 18],
  ['South Africa', 'ZA', '+27', 19],
  ['Brazil', 'BR', '+55', 20],
  // Remaining countries alphabetically (sort_order 100+)
  ['Afghanistan', 'AF', '+93', 100],
  ['Albania', 'AL', '+355', 101],
  ['Algeria', 'DZ', '+213', 102],
  ['Andorra', 'AD', '+376', 103],
  ['Angola', 'AO', '+244', 104],
  ['Argentina', 'AR', '+54', 105],
  ['Armenia', 'AM', '+374', 106],
  ['Austria', 'AT', '+43', 107],
  ['Azerbaijan', 'AZ', '+994', 108],
  ['Barbados', 'BB', '+1', 109],
  ['Belarus', 'BY', '+375', 110],
  ['Belgium', 'BE', '+32', 111],
  ['Belize', 'BZ', '+501', 112],
  ['Benin', 'BJ', '+229', 113],
  ['Bhutan', 'BT', '+975', 114],
  ['Bolivia', 'BO', '+591', 115],
  ['Bosnia and Herzegovina', 'BA', '+387', 116],
  ['Botswana', 'BW', '+267', 117],
  ['Brunei', 'BN', '+673', 118],
  ['Bulgaria', 'BG', '+359', 119],
  ['Burkina Faso', 'BF', '+226', 120],
  ['Burundi', 'BI', '+257', 121],
  ['Cambodia', 'KH', '+855', 122],
  ['Cameroon', 'CM', '+237', 123],
  ['Chile', 'CL', '+56', 124],
  ['China', 'CN', '+86', 125],
  ['Colombia', 'CO', '+57', 126],
  ['Costa Rica', 'CR', '+506', 127],
  ['Croatia', 'HR', '+385', 128],
  ['Cuba', 'CU', '+53', 129],
  ['Cyprus', 'CY', '+357', 130],
  ['Czech Republic', 'CZ', '+420', 131],
  ['Denmark', 'DK', '+45', 132],
  ['Dominican Republic', 'DO', '+1', 133],
  ['Ecuador', 'EC', '+593', 134],
  ['El Salvador', 'SV', '+503', 135],
  ['Estonia', 'EE', '+372', 136],
  ['Ethiopia', 'ET', '+251', 137],
  ['Fiji', 'FJ', '+679', 138],
  ['Finland', 'FI', '+358', 139],
  ['France', 'FR', '+33', 140],
  ['Gabon', 'GA', '+241', 141],
  ['Georgia', 'GE', '+995', 142],
  ['Ghana', 'GH', '+233', 143],
  ['Greece', 'GR', '+30', 144],
  ['Guatemala', 'GT', '+502', 145],
  ['Honduras', 'HN', '+504', 146],
  ['Hungary', 'HU', '+36', 147],
  ['Iceland', 'IS', '+354', 148],
  ['Indonesia', 'ID', '+62', 149],
  ['Iran', 'IR', '+98', 150],
  ['Iraq', 'IQ', '+964', 151],
  ['Ireland', 'IE', '+353', 152],
  ['Israel', 'IL', '+972', 153],
  ['Italy', 'IT', '+39', 154],
  ['Jamaica', 'JM', '+1', 155],
  ['Japan', 'JP', '+81', 156],
  ['Jordan', 'JO', '+962', 157],
  ['Kazakhstan', 'KZ', '+7', 158],
  ['Kenya', 'KE', '+254', 159],
  ['Kyrgyzstan', 'KG', '+996', 160],
  ['Laos', 'LA', '+856', 161],
  ['Latvia', 'LV', '+371', 162],
  ['Lebanon', 'LB', '+961', 163],
  ['Libya', 'LY', '+218', 164],
  ['Liechtenstein', 'LI', '+423', 165],
  ['Lithuania', 'LT', '+370', 166],
  ['Luxembourg', 'LU', '+352', 167],
  ['Madagascar', 'MG', '+261', 168],
  ['Malawi', 'MW', '+265', 169],
  ['Maldives', 'MV', '+960', 170],
  ['Malta', 'MT', '+356', 171],
  ['Mauritius', 'MU', '+230', 172],
  ['Mexico', 'MX', '+52', 173],
  ['Moldova', 'MD', '+373', 174],
  ['Monaco', 'MC', '+377', 175],
  ['Mongolia', 'MN', '+976', 176],
  ['Morocco', 'MA', '+212', 177],
  ['Mozambique', 'MZ', '+258', 178],
  ['Myanmar', 'MM', '+95', 179],
  ['Namibia', 'NA', '+264', 180],
  ['Nepal', 'NP', '+977', 181],
  ['Netherlands', 'NL', '+31', 182],
  ['New Zealand', 'NZ', '+64', 183],
  ['Nicaragua', 'NI', '+505', 184],
  ['North Korea', 'KP', '+850', 185],
  ['Norway', 'NO', '+47', 186],
  ['Panama', 'PA', '+507', 187],
  ['Papua New Guinea', 'PG', '+675', 188],
  ['Paraguay', 'PY', '+595', 189],
  ['Peru', 'PE', '+51', 190],
  ['Poland', 'PL', '+48', 191],
  ['Portugal', 'PT', '+351', 192],
  ['Romania', 'RO', '+40', 193],
  ['Russia', 'RU', '+7', 194],
  ['Rwanda', 'RW', '+250', 195],
  ['Serbia', 'RS', '+381', 196],
  ['Singapore', 'SG', '+65', 197],
  ['Slovakia', 'SK', '+421', 198],
  ['Slovenia', 'SI', '+386', 199],
  ['Somalia', 'SO', '+252', 200],
  ['South Korea', 'KR', '+82', 201],
  ['South Sudan', 'SS', '+211', 202],
  ['Spain', 'ES', '+34', 203],
  ['Sri Lanka', 'LK', '+94', 204],
  ['Sudan', 'SD', '+249', 205],
  ['Sweden', 'SE', '+46', 206],
  ['Switzerland', 'CH', '+41', 207],
  ['Syria', 'SY', '+963', 208],
  ['Taiwan', 'TW', '+886', 209],
  ['Tajikistan', 'TJ', '+992', 210],
  ['Tanzania', 'TZ', '+255', 211],
  ['Thailand', 'TH', '+66', 212],
  ['Togo', 'TG', '+228', 213],
  ['Trinidad and Tobago', 'TT', '+1', 214],
  ['Tunisia', 'TN', '+216', 215],
  ['Turkey', 'TR', '+90', 216],
  ['Turkmenistan', 'TM', '+993', 217],
  ['Uganda', 'UG', '+256', 218],
  ['Ukraine', 'UA', '+380', 219],
  ['Uruguay', 'UY', '+598', 220],
  ['Uzbekistan', 'UZ', '+998', 221],
  ['Venezuela', 'VE', '+58', 222],
  ['Vietnam', 'VN', '+84', 223],
  ['Yemen', 'YE', '+967', 224],
  ['Zambia', 'ZM', '+260', 225],
  ['Zimbabwe', 'ZW', '+263', 226],
];

const states = {
  'US': [
    ['Alabama', 'AL'], ['Alaska', 'AK'], ['Arizona', 'AZ'], ['Arkansas', 'AR'],
    ['California', 'CA'], ['Colorado', 'CO'], ['Connecticut', 'CT'], ['Delaware', 'DE'],
    ['District of Columbia', 'DC'], ['Florida', 'FL'], ['Georgia', 'GA'], ['Hawaii', 'HI'],
    ['Idaho', 'ID'], ['Illinois', 'IL'], ['Indiana', 'IN'], ['Iowa', 'IA'],
    ['Kansas', 'KS'], ['Kentucky', 'KY'], ['Louisiana', 'LA'], ['Maine', 'ME'],
    ['Maryland', 'MD'], ['Massachusetts', 'MA'], ['Michigan', 'MI'], ['Minnesota', 'MN'],
    ['Mississippi', 'MS'], ['Missouri', 'MO'], ['Montana', 'MT'], ['Nebraska', 'NE'],
    ['Nevada', 'NV'], ['New Hampshire', 'NH'], ['New Jersey', 'NJ'], ['New Mexico', 'NM'],
    ['New York', 'NY'], ['North Carolina', 'NC'], ['North Dakota', 'ND'], ['Ohio', 'OH'],
    ['Oklahoma', 'OK'], ['Oregon', 'OR'], ['Pennsylvania', 'PA'], ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'], ['South Dakota', 'SD'], ['Tennessee', 'TN'], ['Texas', 'TX'],
    ['Utah', 'UT'], ['Vermont', 'VT'], ['Virginia', 'VA'], ['Washington', 'WA'],
    ['West Virginia', 'WV'], ['Wisconsin', 'WI'], ['Wyoming', 'WY'],
  ],
  'IN': [
    ['Andaman and Nicobar Islands', 'AN'], ['Andhra Pradesh', 'AP'], ['Arunachal Pradesh', 'AR'],
    ['Assam', 'AS'], ['Bihar', 'BR'], ['Chandigarh', 'CH'], ['Chhattisgarh', 'CG'],
    ['Dadra and Nagar Haveli and Daman and Diu', 'DN'], ['Delhi', 'DL'], ['Goa', 'GA'],
    ['Gujarat', 'GJ'], ['Haryana', 'HR'], ['Himachal Pradesh', 'HP'], ['Jammu and Kashmir', 'JK'],
    ['Jharkhand', 'JH'], ['Karnataka', 'KA'], ['Kerala', 'KL'], ['Ladakh', 'LA'],
    ['Lakshadweep', 'LD'], ['Madhya Pradesh', 'MP'], ['Maharashtra', 'MH'], ['Manipur', 'MN'],
    ['Meghalaya', 'ML'], ['Mizoram', 'MZ'], ['Nagaland', 'NL'], ['Odisha', 'OD'],
    ['Puducherry', 'PY'], ['Punjab', 'PB'], ['Rajasthan', 'RJ'], ['Sikkim', 'SK'],
    ['Tamil Nadu', 'TN'], ['Telangana', 'TG'], ['Tripura', 'TR'], ['Uttar Pradesh', 'UP'],
    ['Uttarakhand', 'UK'], ['West Bengal', 'WB'],
  ],
  'AE': [
    ['Abu Dhabi', 'AZ'], ['Ajman', 'AJ'], ['Dubai', 'DU'], ['Fujairah', 'FU'],
    ['Ras Al Khaimah', 'RK'], ['Sharjah', 'SH'], ['Umm Al Quwain', 'UQ'],
  ],
  'GB': [
    ['England', 'ENG'], ['Northern Ireland', 'NIR'], ['Scotland', 'SCT'], ['Wales', 'WLS'],
  ],
  'AU': [
    ['Australian Capital Territory', 'ACT'], ['New South Wales', 'NSW'],
    ['Northern Territory', 'NT'], ['Queensland', 'QLD'], ['South Australia', 'SA'],
    ['Tasmania', 'TAS'], ['Victoria', 'VIC'], ['Western Australia', 'WA'],
  ],
  'CA': [
    ['Alberta', 'AB'], ['British Columbia', 'BC'], ['Manitoba', 'MB'],
    ['New Brunswick', 'NB'], ['Newfoundland and Labrador', 'NL'], ['Northwest Territories', 'NT'],
    ['Nova Scotia', 'NS'], ['Nunavut', 'NU'], ['Ontario', 'ON'],
    ['Prince Edward Island', 'PE'], ['Quebec', 'QC'], ['Saskatchewan', 'SK'], ['Yukon', 'YT'],
  ],
  'DE': [
    ['Baden-Württemberg', 'BW'], ['Bavaria', 'BY'], ['Berlin', 'BE'], ['Brandenburg', 'BB'],
    ['Bremen', 'HB'], ['Hamburg', 'HH'], ['Hesse', 'HE'], ['Lower Saxony', 'NI'],
    ['Mecklenburg-Vorpommern', 'MV'], ['North Rhine-Westphalia', 'NW'], ['Rhineland-Palatinate', 'RP'],
    ['Saarland', 'SL'], ['Saxony', 'SN'], ['Saxony-Anhalt', 'ST'],
    ['Schleswig-Holstein', 'SH'], ['Thuringia', 'TH'],
  ],
  'SA': [
    ['Al-Bahah', 'BA'], ['Al-Jawf', 'JF'], ['Al Madinah', 'MD'], ['Al-Qassim', 'QS'],
    ['Asir', 'AS'], ['Eastern Province', 'EP'], ["Ha'il", 'HL'], ['Jizan', 'JZ'],
    ['Makkah', 'MK'], ['Najran', 'NJ'], ["Riyadh", 'RD'], ['Tabuk', 'TB'],
    ['Northern Borders', 'NB'],
  ],
  'QA': [
    ['Ad Dawhah (Doha)', 'DA'], ['Al Khor', 'KH'], ['Al Rayyan', 'RA'], ['Al Wakrah', 'WA'],
    ['Al Shamal', 'SH'], ['Madinat ash Shamal', 'MS'], ['Umm Salal', 'US'],
    ['Al Daayen', 'ZA'],
  ],
  'KW': [
    ['Al Ahmadi', 'AH'], ['Al Farwaniyah', 'FA'], ['Al Jahra', 'JA'],
    ['Capital (Kuwait City)', 'KU'], ['Hawalli', 'HA'], ['Mubarak Al-Kabeer', 'MK'],
  ],
  'OM': [
    ['Ad Dakhiliyah', 'DA'], ['Al Batinah North', 'BN'], ['Al Batinah South', 'BS'],
    ['Al Buraymi', 'BU'], ['Al Wusta', 'WU'], ['Ash Sharqiyah North', 'SN'],
    ['Ash Sharqiyah South', 'SS'], ['Dhofar', 'ZU'], ['Musandam', 'MU'],
    ['Muscat', 'MA'], ['Adh Dhahirah', 'ZA'],
  ],
  'BH': [
    ['Capital', 'CA'], ['Central', 'CE'], ['Muharraq', 'MU'], ['Northern', 'NO'],
  ],
  'BR': [
    ['Acre', 'AC'], ['Alagoas', 'AL'], ['Amapá', 'AP'], ['Amazonas', 'AM'],
    ['Bahia', 'BA'], ['Ceará', 'CE'], ['Distrito Federal', 'DF'], ['Espírito Santo', 'ES'],
    ['Goiás', 'GO'], ['Maranhão', 'MA'], ['Mato Grosso', 'MT'], ['Mato Grosso do Sul', 'MS'],
    ['Minas Gerais', 'MG'], ['Pará', 'PA'], ['Paraíba', 'PB'], ['Paraná', 'PR'],
    ['Pernambuco', 'PE'], ['Piauí', 'PI'], ['Rio de Janeiro', 'RJ'], ['Rio Grande do Norte', 'RN'],
    ['Rio Grande do Sul', 'RS'], ['Rondônia', 'RO'], ['Roraima', 'RR'], ['Santa Catarina', 'SC'],
    ['São Paulo', 'SP'], ['Sergipe', 'SE'], ['Tocantins', 'TO'],
  ],
  'MX': [
    ['Aguascalientes', 'AG'], ['Baja California', 'BC'], ['Baja California Sur', 'BS'],
    ['Campeche', 'CM'], ['Chiapas', 'CS'], ['Chihuahua', 'CH'], ['Coahuila', 'CO'],
    ['Colima', 'CL'], ['Durango', 'DG'], ['Guanajuato', 'GT'], ['Guerrero', 'GR'],
    ['Hidalgo', 'HG'], ['Jalisco', 'JA'], ['Mexico City', 'DF'], ['Mexico State', 'ME'],
    ['Michoacán', 'MI'], ['Morelos', 'MO'], ['Nayarit', 'NA'], ['Nuevo León', 'NL'],
    ['Oaxaca', 'OA'], ['Puebla', 'PU'], ['Querétaro', 'QT'], ['Quintana Roo', 'QR'],
    ['San Luis Potosí', 'SL'], ['Sinaloa', 'SI'], ['Sonora', 'SO'], ['Tabasco', 'TB'],
    ['Tamaulipas', 'TM'], ['Tlaxcala', 'TL'], ['Veracruz', 'VE'], ['Yucatán', 'YU'],
    ['Zacatecas', 'ZA'],
  ],
  'FR': [
    ['Auvergne-Rhône-Alpes', 'ARA'], ['Bourgogne-Franche-Comté', 'BFC'],
    ['Bretagne', 'BRE'], ['Centre-Val de Loire', 'CVL'], ['Corse', 'COR'],
    ['Grand Est', 'GES'], ['Guadeloupe', 'GP'], ['Guyane', 'GF'],
    ['Hauts-de-France', 'HDF'], ['Île-de-France', 'IDF'], ['La Réunion', 'RE'],
    ['Martinique', 'MQ'], ['Mayotte', 'YT'], ['Normandie', 'NOR'],
    ['Nouvelle-Aquitaine', 'NAQ'], ['Occitanie', 'OCC'],
    ["Pays de la Loire", 'PDL'], ["Provence-Alpes-Côte d'Azur", 'PAC'],
  ],
  'IT': [
    ['Abruzzo', 'AB'], ['Aosta Valley', 'AO'], ['Apulia', 'PU'], ['Basilicata', 'BT'],
    ['Calabria', 'CZ'], ['Campania', 'NA'], ['Emilia-Romagna', 'BO'], ['Friuli-Venezia Giulia', 'UD'],
    ['Lazio', 'RM'], ['Liguria', 'GE'], ['Lombardy', 'MI'], ['Marche', 'AN'],
    ['Molise', 'CB'], ['Piedmont', 'TO'], ['Sardinia', 'CA'], ['Sicily', 'PA'],
    ['Trentino-South Tyrol', 'TN'], ['Tuscany', 'FI'], ['Umbria', 'PG'], ['Veneto', 'VE'],
  ],
  'ES': [
    ['Andalusia', 'AN'], ['Aragon', 'AR'], ['Asturias', 'AS'], ['Balearic Islands', 'IB'],
    ['Basque Country', 'PV'], ['Canary Islands', 'CN'], ['Cantabria', 'CB'],
    ['Castile-La Mancha', 'CM'], ['Castile and León', 'CL'], ['Catalonia', 'CT'],
    ['Ceuta', 'CE'], ['Extremadura', 'EX'], ['Galicia', 'GA'], ['La Rioja', 'RI'],
    ['Madrid', 'MD'], ['Melilla', 'ML'], ['Murcia', 'MC'],
    ['Navarre', 'NA'], ['Valencia', 'VC'],
  ],
  'PK': [
    ['Azad Kashmir', 'AK'], ['Balochistan', 'BA'], ['Gilgit-Baltistan', 'GB'],
    ['Islamabad Capital Territory', 'IS'], ['Khyber Pakhtunkhwa', 'KP'],
    ['Punjab', 'PB'], ['Sindh', 'SD'],
  ],
  'BD': [
    ['Barisal', 'A'], ['Chittagong', 'B'], ['Dhaka', 'C'], ['Khulna', 'D'],
    ['Mymensingh', 'H'], ['Rajshahi', 'E'], ['Rangpur', 'F'], ['Sylhet', 'G'],
  ],
  'ZA': [
    ['Eastern Cape', 'EC'], ['Free State', 'FS'], ['Gauteng', 'GP'], ['KwaZulu-Natal', 'KZN'],
    ['Limpopo', 'LP'], ['Mpumalanga', 'MP'], ['Northern Cape', 'NC'],
    ['North West', 'NW'], ['Western Cape', 'WC'],
  ],
  'PH': [
    ['Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM'],
    ['Bicol Region', 'V'], ['Cagayan Valley', 'II'], ['Calabarzon', 'IVA'],
    ['Caraga', 'XIII'], ['Central Luzon', 'III'], ['Central Visayas', 'VII'],
    ['Cordillera Administrative Region', 'CAR'], ['Davao Region', 'XI'],
    ['Eastern Visayas', 'VIII'], ['Ilocos Region', 'I'], ['Metro Manila', 'NCR'],
    ['Mimaropa', 'IVB'], ['Northern Mindanao', 'X'], ['Soccsksargen', 'XII'],
    ['Western Visayas', 'VI'], ['Zamboanga Peninsula', 'IX'],
  ],
  'MY': [
    ['Johor', 'JHR'], ['Kedah', 'KDH'], ['Kelantan', 'KTN'], ['Kuala Lumpur', 'KUL'],
    ['Labuan', 'LBN'], ['Melaka', 'MLK'], ['Negeri Sembilan', 'NSN'], ['Pahang', 'PHG'],
    ['Penang', 'PNG'], ['Perak', 'PRK'], ['Perlis', 'PLS'], ['Putrajaya', 'PJY'],
    ['Sabah', 'SBH'], ['Sarawak', 'SWK'], ['Selangor', 'SGR'], ['Terengganu', 'TRG'],
  ],
  'NG': [
    ['Abia', 'AB'], ['Adamawa', 'AD'], ['Akwa Ibom', 'AK'], ['Anambra', 'AN'],
    ['Bauchi', 'BA'], ['Bayelsa', 'BY'], ['Benue', 'BE'], ['Borno', 'BO'],
    ['Cross River', 'CR'], ['Delta', 'DE'], ['Ebonyi', 'EB'], ['Edo', 'ED'],
    ['Ekiti', 'EK'], ['Enugu', 'EN'], ['Federal Capital Territory', 'FC'], ['Gombe', 'GO'],
    ['Imo', 'IM'], ['Jigawa', 'JI'], ['Kaduna', 'KD'], ['Kano', 'KN'], ['Katsina', 'KT'],
    ['Kebbi', 'KB'], ['Kogi', 'KO'], ['Kwara', 'KW'], ['Lagos', 'LA'], ['Nasarawa', 'NA'],
    ['Niger', 'NI'], ['Ogun', 'OG'], ['Ondo', 'ON'], ['Osun', 'OS'], ['Oyo', 'OY'],
    ['Plateau', 'PL'], ['Rivers', 'RI'], ['Sokoto', 'SO'], ['Taraba', 'TA'],
    ['Yobe', 'YO'], ['Zamfara', 'ZA'],
  ],
  'EG': [
    ['Alexandria', 'ALX'], ['Aswan', 'ASN'], ['Asyut', 'AST'], ['Beheira', 'BH'],
    ['Beni Suef', 'BNS'], ['Cairo', 'C'], ['Dakahlia', 'DK'], ['Damietta', 'DT'],
    ['Faiyum', 'FYM'], ['Gharbia', 'GH'], ['Giza', 'GZ'], ['Ismailia', 'IS'],
    ['Kafr El Sheikh', 'KFS'], ['Luxor', 'LX'], ['Matruh', 'MT'], ['Minya', 'MN'],
    ['Monufia', 'MNF'], ['New Valley', 'WAD'], ['North Sinai', 'SIN'], ['Port Said', 'PTS'],
    ['Qalyubia', 'KB'], ['Qena', 'KN'], ['Red Sea', 'BA'], ['Sharqia', 'SHR'],
    ['Sohag', 'SHG'], ['South Sinai', 'JS'], ['Suez', 'SUZ'],
  ],
  'TR': [
    ['Aegean', 'AEG'], ['Black Sea', 'BS'], ['Central Anatolia', 'CA'],
    ['Eastern Anatolia', 'EA'], ['Marmara', 'MAR'], ['Mediterranean', 'MED'],
    ['Southeastern Anatolia', 'SEA'],
  ],
  'KR': [
    ['Busan', 'BS'], ['Chungcheongbuk-do', 'CB'], ['Chungcheongnam-do', 'CN'],
    ['Daegu', 'DG'], ['Daejeon', 'DJ'], ['Gangwon-do', 'GW'], ['Gwangju', 'GJ'],
    ['Gyeonggi-do', 'GG'], ['Gyeongsangbuk-do', 'GB'], ['Gyeongsangnam-do', 'GN'],
    ['Incheon', 'IN'], ['Jeju', 'JE'], ['Jeollabuk-do', 'JB'], ['Jeollanam-do', 'JN'],
    ['Sejong', 'SJ'], ['Seoul', 'SE'], ['Ulsan', 'UL'],
  ],
  'JP': [
    ['Chubu', 'CHB'], ['Chugoku', 'CGK'], ['Hokkaido', 'HKD'], ['Kansai', 'KNS'],
    ['Kanto', 'KNT'], ['Kyushu', 'KYU'], ['Shikoku', 'SHK'], ['Tohoku', 'THK'],
  ],
  'ID': [
    ['Bali', 'BA'], ['Java', 'JV'], ['Kalimantan', 'KA'], ['Maluku', 'MA'],
    ['Papua', 'PA'], ['Sulawesi', 'SU'], ['Sumatra', 'SM'],
  ],
};

function seedGeo(db) {
  const count = db.prepare('SELECT COUNT(*) as c FROM geo_countries').get();
  if (count && count.c > 0) return; // already seeded

  const insertCountry = db.prepare(
    'INSERT OR IGNORE INTO geo_countries(name, iso2, phone_code, sort_order) VALUES(?,?,?,?)'
  );
  const insertState = db.prepare(
    'INSERT OR IGNORE INTO geo_states(country_id, name, code) VALUES(?,?,?)'
  );

  db.transaction(() => {
    for (const [name, iso2, phone_code, sort_order] of countries) {
      insertCountry.run(name, iso2, phone_code, sort_order);
    }
    for (const [iso2, stateList] of Object.entries(states)) {
      const country = db.prepare('SELECT id FROM geo_countries WHERE iso2=?').get(iso2);
      if (!country) continue;
      for (const [sname, scode] of stateList) {
        insertState.run(country.id, sname, scode);
      }
    }
  })();
  console.log('Database: geo data seeded (', countries.length, 'countries)');
}

module.exports = { countries, states, seedGeo };
